  version: '2'
  services:
    # MongoDB: https://hub.docker.com/_/mongo/
    mongodb:
      container_name: mongodb
      image: mongo:4.2
      volumes:
        - mongo_data:/data/db
      restart: always
    # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
    elasticsearch:
      container_name: elasticsearch    
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
      volumes:
        - es_data:/usr/share/elasticsearch/data
        - elastic-backup-remote:/usr/share/elasticsearch/backup
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ./jvm.options:/usr/share/elasticsearch/config/jvm.options
      environment:
        - node.name=elasticsearch
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Xms10g -Xmx10g -Dlog4j2.formatMsgNolookups=true"
      ports:
      - 9200:9200
      ulimits:
        memlock:
          soft: -12
          hard: -12
      mem_limit: 12g
      restart: always
    # Graylog: https://hub.docker.com/r/graylog/graylog/
    graylog:
      image: graylog/graylog:4.2
      container_name: graylog
      volumes:
        - graylog_data:/usr/share/graylog/data
        - graylog_journal:/usr/share/graylog/data/journal

      environment:
        #timezone adaptation
        - TZ=CET
        - GRAYLOG_TIMEZONE=CET
        - GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/config/node-id
        - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
        - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
        # CHANGE ME (must be at least 16 characters)!
        - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
        # Password: admin
        - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
        - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
        - GRAYLOG_ELASTICSEARCH_VERSION=7
      entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh

      restart: always
      depends_on:
        mongodb:
          condition : "service_started"
        elasticsearch: 
          condition : "service_started"
      ports:
        # Graylog web interface and REST API
        - 9000:9000
        # Syslog TCP
        - 514:514
        - 1514:1514
        - 5044:5044 #sidecar
        - 5555:5555 #raw TCP
        - 5555:5555/udp #raw udp 
        # Syslog UDP
        - 514:514/udp
        - 1514:1514/udp
        # GELF TCP
        - 12201:12201
        # GELF UDP
        - 12201:12201/udp
        - 13302:13302/tcp #forwarder data
        - 13301:13301/tcp #forwarder config
        # Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
          # kibana https://www.elastic.co/guide/en/kibana/7.10/docker.html
    #kibana:
     # container_name: kibana
      #image: docker.elastic.co/kibana/kibana:7.10.2
      #ports:
       # - 5601:5601
      #environment:
       # ELASTICSEARCH_URL: http://es01:9200
        #ELASTICSEARCH_HOSTS: http://es01:9200
      #volumes:
       # - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      #restart: always
      #depends_on:
       # elasticsearch: 
        #  condition : "service_started"
  volumes:
    mongo_data:
      driver: local
    es_data:
      driver: local
    graylog_data:
      driver: local
    graylog_journal:
      driver: local
    elastic-backup-remote:
      driver_opts:
        type: cifs
        o: addr=192.168.0.185,username=${username},password=${password},file_mode=0777,dir_mode=0777
        device: "//192.168.0.185/esbackup/backup/"
