<<<<<<< HEAD:Docker-compose.yml
version: "3.8"

services:
  mongodb1:
    image: "mongo:4.2"
    hostname: "mongodb1"
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - "mongodb-data-01:/data/db"
      - "./mongodb/initdb.d:/docker-entrypoint-initdb.d"
      - "./mongodb/init-replset.js:/init-replset.js"
    restart: "on-failure"

  mongodb2:
    image: "mongo:4.2"
    hostname: "mongodb2"
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - "mongodb-data-02:/data/db"
    restart: "on-failure"

  mongodb3:
    image: "mongo:4.2"
    hostname: "mongodb3"
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - "mongodb-data-03:/data/db"
    restart: "on-failure"

  elasticsearch1:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    hostname: "elasticsearch1"
    environment:
      node.name: "elasticsearch1"
      cluster.name: "es-docker-cluster"
      discovery.seed_hosts: "elasticsearch2,elasticsearch3"
      cluster.initial_master_nodes: "elasticsearch1,elasticsearch2,elasticsearch3"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "elasticsearch-data-01:/usr/share/elasticsearch/data"
    restart: "on-failure"

  elasticsearch2:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    hostname: "elasticsearch2"
    environment:
      node.name: "elasticsearch2"
      cluster.name: "es-docker-cluster"
      discovery.seed_hosts: "elasticsearch1,elasticsearch3"
      cluster.initial_master_nodes: "elasticsearch1,elasticsearch2,elasticsearch3"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "elasticsearch-data-02:/usr/share/elasticsearch/data"
    restart: "on-failure"

  elasticsearch3:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    hostname: "elasticsearch3"
    environment:
      node.name: "elasticsearch3"
      cluster.name: "es-docker-cluster"
      discovery.seed_hosts: "elasticsearch1,elasticsearch2"
      cluster.initial_master_nodes: "elasticsearch1,elasticsearch2,elasticsearch3"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "elasticsearch-data-03:/usr/share/elasticsearch/data"
    restart: "on-failure"

  graylog1:
    image: "graylog/graylog:4.2"
    hostname: "graylog1"
    depends_on:
      - "mongodb1"
      - "mongodb2"
      - "mongodb3"
      - "elasticsearch1"
      - "elasticsearch2"
      - "elasticsearch3"
    entrypoint: "/docker-entrypoint.sh"
    environment:
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch1:9200,http://elasticsearch2:9201,http://elasticsearch3:9202"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb1:27017,mongodb2:27017,mongodb3:27017/graylog"
    ports:
      - "9000:9000"        # Graylog web interface and REST API
      - "1514:1514"        # Syslog TCP
      - "1514:1514/udp"    # Syslog UDP
      - "12201:12201"      # GELF TCP
      - "12201:12201/udp"  # GELF UDP
    volumes:
      - "graylog-data-01:/usr/share/graylog/data/data"
      - "graylog-journal-01:/usr/share/graylog/data/journal"
    restart: "on-failure"

  graylog2:
    image: "graylog/graylog:4.2"
    hostname: "graylog2"
    depends_on:
      - "mongodb1"
      - "mongodb2"
      - "mongodb3"
      - "elasticsearch1"
      - "elasticsearch2"
      - "elasticsearch3"
    entrypoint: "/docker-entrypoint.sh"
    environment:
      GRAYLOG_IS_MASTER: "false"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9001"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch1:9200,http://elasticsearch2:9201,http://elasticsearch3:9202"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb1:27017,mongodb2:27017,mongodb3:27017/graylog"
    ports:
      - "9001:9001"         # Graylog web interface and REST API
      - "1515:1514"         # Syslog TCP
      - "1515:1514/udp"     # Syslog UDP
      - "12202:12201"       # GELF TCP
      - "12202:12201/udp"   # GELF UDP
    volumes:
      - "graylog-data-02:/usr/share/graylog/data/data"
      - "graylog-journal-02:/usr/share/graylog/data/journal"
    restart: "on-failure"

  graylog3:
    image: "graylog/graylog:4.2"
    hostname: "graylog3"
    depends_on:
      - "mongodb1"
      - "mongodb2"
      - "mongodb3"
      - "elasticsearch1"
      - "elasticsearch2"
      - "elasticsearch3"
    entrypoint: "/docker-entrypoint.sh"
    environment:
      GRAYLOG_IS_MASTER: "false"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9002"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch1:9200,http://elasticsearch2:9201,http://elasticsearch3:9202"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb1:27017,mongodb2:27017,mongodb3:27017/graylog"
    ports:
      - "9002:9002"       # Graylog web interface and REST API
      - "1516:1514"       # Syslog TCP
      - "1516:1514/udp"   # Syslog UDP
      - "12203:12201"     # GELF TCP
      - "12203:12201/udp" # GELF UDP
    volumes:
      - "graylog-data-03:/usr/share/graylog/data/data"
      - "graylog-journal-03:/usr/share/graylog/data/journal"
    restart: "on-failure"

volumes:
  elasticsearch-data-01:
  elasticsearch-data-02:
  elasticsearch-data-03:
  graylog-data-01:
  graylog-data-02:
  graylog-data-03:
  graylog-journal-01:
  graylog-journal-02:
  graylog-journal-03:
  mongodb-data-01:
  mongodb-data-02:
  mongodb-data-03:
=======
  version: '2'
  services:
    # MongoDB: https://hub.docker.com/_/mongo/
    mongodb:
      image: mongo:4.2
      volumes:
        - mongo_data:/data/db
    # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
    elasticsearch:
      image: elastic:9
      volumes:
        - es_data:/usr/share/elasticsearch/data
      environment:
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      ulimits:
        memlock:
          soft: -2
          hard: -2
      mem_limit: 2g
    # Graylog: https://hub.docker.com/r/graylog/graylog/
    graylog:
      image: graylog/graylog:4.2
      volumes:
        - graylog_data:/usr/share/graylog/data
      environment:
        #timezone adaptation
        - TZ=CET
        - GRAYLOG_TIMEZONE=CET
        # CHANGE ME (must be at least 16 characters)!
        - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
        # Password: admin
        - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.91.91:9000/
      entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
      links:
        - mongodb:mongo
        - elasticsearch
      restart: always
      depends_on:
        - mongodb
        - elasticsearch
      ports:
        # Graylog web interface and REST API
        - 9000:9000
        # Syslog TCP
        - 514:1514
        - 1514:1514
        #sidecar
        - 5044:5044
        # Syslog UDP
        - 514:1514/udp
        - 1514:1514/udp
        # GELF TCP
        - 12201:12201
        # GELF UDP
        - 12201:12201/udp
        # Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
  volumes:
    mongo_data:
      driver: local
    es_data:
      driver: local
    graylog_data:
      driver: local
>>>>>>> 9bbea89111756d236ecd590057a083c2bc185c1e:docker-compose.yml
